// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0O0gwblWzK4O3aAlU2oWySvGC46yWx3k',
    appId: '1:240771324668:web:beb063ecef253e5c76d579',
    messagingSenderId: '240771324668',
    projectId: 'dompetkos-57b72',
    authDomain: 'dompetkos-57b72.firebaseapp.com',
    storageBucket: 'dompetkos-57b72.appspot.com',
    measurementId: 'G-1CMJDFGRSH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5hTs2jNy4CiGGex9X4UcBNAKUV6Db4RA',
    appId: '1:240771324668:android:088b5caff5f1692376d579',
    messagingSenderId: '240771324668',
    projectId: 'dompetkos-57b72',
    storageBucket: 'dompetkos-57b72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOOAczumrPE5AOF9_KVPWS4LIKSg9IpPA',
    appId: '1:240771324668:ios:f432852527a1be8e76d579',
    messagingSenderId: '240771324668',
    projectId: 'dompetkos-57b72',
    storageBucket: 'dompetkos-57b72.appspot.com',
    iosBundleId: 'com.example.dompetkos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOOAczumrPE5AOF9_KVPWS4LIKSg9IpPA',
    appId: '1:240771324668:ios:f432852527a1be8e76d579',
    messagingSenderId: '240771324668',
    projectId: 'dompetkos-57b72',
    storageBucket: 'dompetkos-57b72.appspot.com',
    iosBundleId: 'com.example.dompetkos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0O0gwblWzK4O3aAlU2oWySvGC46yWx3k',
    appId: '1:240771324668:web:9c607ec8f4790fa376d579',
    messagingSenderId: '240771324668',
    projectId: 'dompetkos-57b72',
    authDomain: 'dompetkos-57b72.firebaseapp.com',
    storageBucket: 'dompetkos-57b72.appspot.com',
    measurementId: 'G-XW7ZK6JD2M',
  );
}
